url_base: http://localhost/sdmx_172/ws/NODE_API/
nodeId: 'ESC01'
languages:
  - en
  - es
extractor_path: /home/prada/PycharmProjects/IECA-extractor/
translate: False
cache: configuracion/traducciones.yaml